public func curry<A, B>(function: (A) throws -> B) -> A throws -> B {
    return { (`a`: A) throws -> B in try function(`a`) }
}

public func curry<A, B, C>(function: (A, B) throws -> C) -> A -> B throws -> C {
    return { (`a`: A) -> B throws -> C in { (`b`: B) throws -> C in try function(`a`, `b`) } }
}

public func curry<A, B, C, D>(function: (A, B, C) throws -> D) -> A -> B -> C throws -> D {
    return { (`a`: A) -> B -> C throws -> D in { (`b`: B) -> C throws -> D in { (`c`: C) throws -> D in try function(`a`, `b`, `c`) } } }
}

public func curry<A, B, C, D, E>(function: (A, B, C, D) throws -> E) -> A -> B -> C -> D throws -> E {
    return { (`a`: A) -> B -> C -> D throws -> E in { (`b`: B) -> C -> D throws -> E in { (`c`: C) -> D throws -> E in { (`d`: D) throws -> E in try function(`a`, `b`, `c`, `d`) } } } }
}

public func curry<A, B, C, D, E, F>(function: (A, B, C, D, E) throws -> F) -> A -> B -> C -> D -> E throws -> F {
    return { (`a`: A) -> B -> C -> D -> E throws -> F in { (`b`: B) -> C -> D -> E throws -> F in { (`c`: C) -> D -> E throws -> F in { (`d`: D) -> E throws -> F in { (`e`: E) throws -> F in try function(`a`, `b`, `c`, `d`, `e`) } } } } }
}

public func curry<A, B, C, D, E, F, G>(function: (A, B, C, D, E, F) throws -> G) -> A -> B -> C -> D -> E -> F throws -> G {
    return { (`a`: A) -> B -> C -> D -> E -> F throws -> G in { (`b`: B) -> C -> D -> E -> F throws -> G in { (`c`: C) -> D -> E -> F throws -> G in { (`d`: D) -> E -> F throws -> G in { (`e`: E) -> F throws -> G in { (`f`: F) throws -> G in try function(`a`, `b`, `c`, `d`, `e`, `f`) } } } } } }
}

public func curry<A, B, C, D, E, F, G, H>(function: (A, B, C, D, E, F, G) throws -> H) -> A -> B -> C -> D -> E -> F -> G throws -> H {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G throws -> H in { (`b`: B) -> C -> D -> E -> F -> G throws -> H in { (`c`: C) -> D -> E -> F -> G throws -> H in { (`d`: D) -> E -> F -> G throws -> H in { (`e`: E) -> F -> G throws -> H in { (`f`: F) -> G throws -> H in { (`g`: G) throws -> H in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`) } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I>(function: (A, B, C, D, E, F, G, H) throws -> I) -> A -> B -> C -> D -> E -> F -> G -> H throws -> I {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H throws -> I in { (`b`: B) -> C -> D -> E -> F -> G -> H throws -> I in { (`c`: C) -> D -> E -> F -> G -> H throws -> I in { (`d`: D) -> E -> F -> G -> H throws -> I in { (`e`: E) -> F -> G -> H throws -> I in { (`f`: F) -> G -> H throws -> I in { (`g`: G) -> H throws -> I in { (`h`: H) throws -> I in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`) } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J>(function: (A, B, C, D, E, F, G, H, I) throws -> J) -> A -> B -> C -> D -> E -> F -> G -> H -> I throws -> J {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I throws -> J in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I throws -> J in { (`c`: C) -> D -> E -> F -> G -> H -> I throws -> J in { (`d`: D) -> E -> F -> G -> H -> I throws -> J in { (`e`: E) -> F -> G -> H -> I throws -> J in { (`f`: F) -> G -> H -> I throws -> J in { (`g`: G) -> H -> I throws -> J in { (`h`: H) -> I throws -> J in { (`i`: I) throws -> J in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`) } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K>(function: (A, B, C, D, E, F, G, H, I, J) throws -> K) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J throws -> K {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J throws -> K in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J throws -> K in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J throws -> K in { (`d`: D) -> E -> F -> G -> H -> I -> J throws -> K in { (`e`: E) -> F -> G -> H -> I -> J throws -> K in { (`f`: F) -> G -> H -> I -> J throws -> K in { (`g`: G) -> H -> I -> J throws -> K in { (`h`: H) -> I -> J throws -> K in { (`i`: I) -> J throws -> K in { (`j`: J) throws -> K in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`) } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L>(function: (A, B, C, D, E, F, G, H, I, J, K) throws -> L) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K throws -> L {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K throws -> L in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K throws -> L in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K throws -> L in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K throws -> L in { (`e`: E) -> F -> G -> H -> I -> J -> K throws -> L in { (`f`: F) -> G -> H -> I -> J -> K throws -> L in { (`g`: G) -> H -> I -> J -> K throws -> L in { (`h`: H) -> I -> J -> K throws -> L in { (`i`: I) -> J -> K throws -> L in { (`j`: J) -> K throws -> L in { (`k`: K) throws -> L in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`) } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M>(function: (A, B, C, D, E, F, G, H, I, J, K, L) throws -> M) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L throws -> M {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L throws -> M in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L throws -> M in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L throws -> M in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L throws -> M in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L throws -> M in { (`f`: F) -> G -> H -> I -> J -> K -> L throws -> M in { (`g`: G) -> H -> I -> J -> K -> L throws -> M in { (`h`: H) -> I -> J -> K -> L throws -> M in { (`i`: I) -> J -> K -> L throws -> M in { (`j`: J) -> K -> L throws -> M in { (`k`: K) -> L throws -> M in { (`l`: L) throws -> M in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`) } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M) throws -> N) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M throws -> N {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M throws -> N in { (`g`: G) -> H -> I -> J -> K -> L -> M throws -> N in { (`h`: H) -> I -> J -> K -> L -> M throws -> N in { (`i`: I) -> J -> K -> L -> M throws -> N in { (`j`: J) -> K -> L -> M throws -> N in { (`k`: K) -> L -> M throws -> N in { (`l`: L) -> M throws -> N in { (`m`: M) throws -> N in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`) } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N) throws -> O) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N throws -> O in { (`h`: H) -> I -> J -> K -> L -> M -> N throws -> O in { (`i`: I) -> J -> K -> L -> M -> N throws -> O in { (`j`: J) -> K -> L -> M -> N throws -> O in { (`k`: K) -> L -> M -> N throws -> O in { (`l`: L) -> M -> N throws -> O in { (`m`: M) -> N throws -> O in { (`n`: N) throws -> O in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`) } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O) throws -> P) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O throws -> P in { (`i`: I) -> J -> K -> L -> M -> N -> O throws -> P in { (`j`: J) -> K -> L -> M -> N -> O throws -> P in { (`k`: K) -> L -> M -> N -> O throws -> P in { (`l`: L) -> M -> N -> O throws -> P in { (`m`: M) -> N -> O throws -> P in { (`n`: N) -> O throws -> P in { (`o`: O) throws -> P in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`) } } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P) throws -> Q) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`i`: I) -> J -> K -> L -> M -> N -> O -> P throws -> Q in { (`j`: J) -> K -> L -> M -> N -> O -> P throws -> Q in { (`k`: K) -> L -> M -> N -> O -> P throws -> Q in { (`l`: L) -> M -> N -> O -> P throws -> Q in { (`m`: M) -> N -> O -> P throws -> Q in { (`n`: N) -> O -> P throws -> Q in { (`o`: O) -> P throws -> Q in { (`p`: P) throws -> Q in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`) } } } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q) throws -> R) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`j`: J) -> K -> L -> M -> N -> O -> P -> Q throws -> R in { (`k`: K) -> L -> M -> N -> O -> P -> Q throws -> R in { (`l`: L) -> M -> N -> O -> P -> Q throws -> R in { (`m`: M) -> N -> O -> P -> Q throws -> R in { (`n`: N) -> O -> P -> Q throws -> R in { (`o`: O) -> P -> Q throws -> R in { (`p`: P) -> Q throws -> R in { (`q`: Q) throws -> R in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`) } } } } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R) throws -> S) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`k`: K) -> L -> M -> N -> O -> P -> Q -> R throws -> S in { (`l`: L) -> M -> N -> O -> P -> Q -> R throws -> S in { (`m`: M) -> N -> O -> P -> Q -> R throws -> S in { (`n`: N) -> O -> P -> Q -> R throws -> S in { (`o`: O) -> P -> Q -> R throws -> S in { (`p`: P) -> Q -> R throws -> S in { (`q`: Q) -> R throws -> S in { (`r`: R) throws -> S in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`) } } } } } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S) throws -> T) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`k`: K) -> L -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`l`: L) -> M -> N -> O -> P -> Q -> R -> S throws -> T in { (`m`: M) -> N -> O -> P -> Q -> R -> S throws -> T in { (`n`: N) -> O -> P -> Q -> R -> S throws -> T in { (`o`: O) -> P -> Q -> R -> S throws -> T in { (`p`: P) -> Q -> R -> S throws -> T in { (`q`: Q) -> R -> S throws -> T in { (`r`: R) -> S throws -> T in { (`s`: S) throws -> T in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`) } } } } } } } } } } } } } } } } } } }
}

public func curry<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(function: (A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T) throws -> U) -> A -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U {
    return { (`a`: A) -> B -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`b`: B) -> C -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`c`: C) -> D -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`d`: D) -> E -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`e`: E) -> F -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`f`: F) -> G -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`g`: G) -> H -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`h`: H) -> I -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`i`: I) -> J -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`j`: J) -> K -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`k`: K) -> L -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`l`: L) -> M -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`m`: M) -> N -> O -> P -> Q -> R -> S -> T throws -> U in { (`n`: N) -> O -> P -> Q -> R -> S -> T throws -> U in { (`o`: O) -> P -> Q -> R -> S -> T throws -> U in { (`p`: P) -> Q -> R -> S -> T throws -> U in { (`q`: Q) -> R -> S -> T throws -> U in { (`r`: R) -> S -> T throws -> U in { (`s`: S) -> T throws -> U in { (`t`: T) throws -> U in try function(`a`, `b`, `c`, `d`, `e`, `f`, `g`, `h`, `i`, `j`, `k`, `l`, `m`, `n`, `o`, `p`, `q`, `r`, `s`, `t`) } } } } } } } } } } } } } } } } } } } }
}
